import { InitialPokeData } from "@/features/pokemon";

export const allPokemon: InitialPokeData[] = [
  { id: 1, name: "bulbasaur", types: ["grass", "poison"], gen: 1 },
  { id: 2, name: "ivysaur", types: ["grass", "poison"], gen: 1 },
  { id: 3, name: "venusaur", types: ["grass", "poison"], gen: 1 },
  { id: 4, name: "charmander", types: ["fire"], gen: 1 },
  { id: 5, name: "charmeleon", types: ["fire"], gen: 1 },
  { id: 6, name: "charizard", types: ["fire", "flying"], gen: 1 },
  { id: 7, name: "squirtle", types: ["water"], gen: 1 },
  { id: 8, name: "wartortle", types: ["water"], gen: 1 },
  { id: 9, name: "blastoise", types: ["water"], gen: 1 },
  { id: 10, name: "caterpie", types: ["bug"], gen: 1 },
  { id: 11, name: "metapod", types: ["bug"], gen: 1 },
  { id: 12, name: "butterfree", types: ["bug", "flying"], gen: 1 },
  { id: 13, name: "weedle", types: ["bug", "poison"], gen: 1 },
  { id: 14, name: "kakuna", types: ["bug", "poison"], gen: 1 },
  { id: 15, name: "beedrill", types: ["bug", "poison"], gen: 1 },
  { id: 16, name: "pidgey", types: ["normal", "flying"], gen: 1 },
  { id: 17, name: "pidgeotto", types: ["normal", "flying"], gen: 1 },
  { id: 18, name: "pidgeot", types: ["normal", "flying"], gen: 1 },
  { id: 19, name: "rattata", types: ["normal"], gen: 1 },
  { id: 20, name: "raticate", types: ["normal"], gen: 1 },
  { id: 21, name: "spearow", types: ["normal", "flying"], gen: 1 },
  { id: 22, name: "fearow", types: ["normal", "flying"], gen: 1 },
  { id: 23, name: "ekans", types: ["poison"], gen: 1 },
  { id: 24, name: "arbok", types: ["poison"], gen: 1 },
  { id: 25, name: "pikachu", types: ["electric"], gen: 1 },
  { id: 26, name: "raichu", types: ["electric"], gen: 1 },
  { id: 27, name: "sandshrew", types: ["ground"], gen: 1 },
  { id: 28, name: "sandslash", types: ["ground"], gen: 1 },
  { id: 29, name: "nidoran\u2640", types: ["poison"], gen: 1 },
  { id: 30, name: "nidorina", types: ["poison"], gen: 1 },
  { id: 31, name: "nidoqueen", types: ["poison", "ground"], gen: 1 },
  { id: 32, name: "nidoran\u2642", types: ["poison"], gen: 1 },
  { id: 33, name: "nidorino", types: ["poison"], gen: 1 },
  { id: 34, name: "nidoking", types: ["poison", "ground"], gen: 1 },
  { id: 35, name: "clefairy", types: ["fairy"], gen: 1 },
  { id: 36, name: "clefable", types: ["fairy"], gen: 1 },
  { id: 37, name: "vulpix", types: ["fire"], gen: 1 },
  { id: 38, name: "ninetales", types: ["fire"], gen: 1 },
  { id: 39, name: "jigglypuff", types: ["normal", "fairy"], gen: 1 },
  { id: 40, name: "wigglytuff", types: ["normal", "fairy"], gen: 1 },
  { id: 41, name: "zubat", types: ["poison", "flying"], gen: 1 },
  { id: 42, name: "golbat", types: ["poison", "flying"], gen: 1 },
  { id: 43, name: "oddish", types: ["grass", "poison"], gen: 1 },
  { id: 44, name: "gloom", types: ["grass", "poison"], gen: 1 },
  { id: 45, name: "vileplume", types: ["grass", "poison"], gen: 1 },
  { id: 46, name: "paras", types: ["bug", "grass"], gen: 1 },
  { id: 47, name: "parasect", types: ["bug", "grass"], gen: 1 },
  { id: 48, name: "venonat", types: ["bug", "poison"], gen: 1 },
  { id: 49, name: "venomoth", types: ["bug", "poison"], gen: 1 },
  { id: 50, name: "diglett", types: ["ground"], gen: 1 },
  { id: 51, name: "dugtrio", types: ["ground"], gen: 1 },
  { id: 52, name: "meowth", types: ["normal"], gen: 1 },
  { id: 53, name: "persian", types: ["normal"], gen: 1 },
  { id: 54, name: "psyduck", types: ["water"], gen: 1 },
  { id: 55, name: "golduck", types: ["water"], gen: 1 },
  { id: 56, name: "mankey", types: ["fighting"], gen: 1 },
  { id: 57, name: "primeape", types: ["fighting"], gen: 1 },
  { id: 58, name: "growlithe", types: ["fire"], gen: 1 },
  { id: 59, name: "arcanine", types: ["fire"], gen: 1 },
  { id: 60, name: "poliwag", types: ["water"], gen: 1 },
  { id: 61, name: "poliwhirl", types: ["water"], gen: 1 },
  { id: 62, name: "poliwrath", types: ["water", "fighting"], gen: 1 },
  { id: 63, name: "abra", types: ["psychic"], gen: 1 },
  { id: 64, name: "kadabra", types: ["psychic"], gen: 1 },
  { id: 65, name: "alakazam", types: ["psychic"], gen: 1 },
  { id: 66, name: "machop", types: ["fighting"], gen: 1 },
  { id: 67, name: "machoke", types: ["fighting"], gen: 1 },
  { id: 68, name: "machamp", types: ["fighting"], gen: 1 },
  { id: 69, name: "bellsprout", types: ["grass", "poison"], gen: 1 },
  { id: 70, name: "weepinbell", types: ["grass", "poison"], gen: 1 },
  { id: 71, name: "victreebel", types: ["grass", "poison"], gen: 1 },
  { id: 72, name: "tentacool", types: ["water", "poison"], gen: 1 },
  { id: 73, name: "tentacruel", types: ["water", "poison"], gen: 1 },
  { id: 74, name: "geodude", types: ["rock", "ground"], gen: 1 },
  { id: 75, name: "graveler", types: ["rock", "ground"], gen: 1 },
  { id: 76, name: "golem", types: ["rock", "ground"], gen: 1 },
  { id: 77, name: "ponyta", types: ["fire"], gen: 1 },
  { id: 78, name: "rapidash", types: ["fire"], gen: 1 },
  { id: 79, name: "slowpoke", types: ["water", "psychic"], gen: 1 },
  { id: 80, name: "slowbro", types: ["water", "psychic"], gen: 1 },
  { id: 81, name: "magnemite", types: ["electric", "steel"], gen: 1 },
  { id: 82, name: "magneton", types: ["electric", "steel"], gen: 1 },
  { id: 83, name: "farfetchd", types: ["normal", "flying"], gen: 1 },
  { id: 84, name: "doduo", types: ["normal", "flying"], gen: 1 },
  { id: 85, name: "dodrio", types: ["normal", "flying"], gen: 1 },
  { id: 86, name: "seel", types: ["water"], gen: 1 },
  { id: 87, name: "dewgong", types: ["water", "ice"], gen: 1 },
  { id: 88, name: "grimer", types: ["poison"], gen: 1 },
  { id: 89, name: "muk", types: ["poison"], gen: 1 },
  { id: 90, name: "shellder", types: ["water"], gen: 1 },
  { id: 91, name: "cloyster", types: ["water", "ice"], gen: 1 },
  { id: 92, name: "gastly", types: ["ghost", "poison"], gen: 1 },
  { id: 93, name: "haunter", types: ["ghost", "poison"], gen: 1 },
  { id: 94, name: "gengar", types: ["ghost", "poison"], gen: 1 },
  { id: 95, name: "onix", types: ["rock", "ground"], gen: 1 },
  { id: 96, name: "drowzee", types: ["psychic"], gen: 1 },
  { id: 97, name: "hypno", types: ["psychic"], gen: 1 },
  { id: 98, name: "krabby", types: ["water"], gen: 1 },
  { id: 99, name: "kingler", types: ["water"], gen: 1 },
  { id: 100, name: "voltorb", types: ["electric"], gen: 1 },
  { id: 101, name: "electrode", types: ["electric"], gen: 1 },
  { id: 102, name: "exeggcute", types: ["grass", "psychic"], gen: 1 },
  { id: 103, name: "exeggutor", types: ["grass", "psychic"], gen: 1 },
  { id: 104, name: "cubone", types: ["ground"], gen: 1 },
  { id: 105, name: "marowak", types: ["ground"], gen: 1 },
  { id: 106, name: "hitmonlee", types: ["fighting"], gen: 1 },
  { id: 107, name: "hitmonchan", types: ["fighting"], gen: 1 },
  { id: 108, name: "lickitung", types: ["normal"], gen: 1 },
  { id: 109, name: "koffing", types: ["poison"], gen: 1 },
  { id: 110, name: "weezing", types: ["poison"], gen: 1 },
  { id: 111, name: "rhyhorn", types: ["ground", "rock"], gen: 1 },
  { id: 112, name: "rhydon", types: ["ground", "rock"], gen: 1 },
  { id: 113, name: "chansey", types: ["normal"], gen: 1 },
  { id: 114, name: "tangela", types: ["grass"], gen: 1 },
  { id: 115, name: "kangaskhan", types: ["normal"], gen: 1 },
  { id: 116, name: "horsea", types: ["water"], gen: 1 },
  { id: 117, name: "seadra", types: ["water"], gen: 1 },
  { id: 118, name: "goldeen", types: ["water"], gen: 1 },
  { id: 119, name: "seaking", types: ["water"], gen: 1 },
  { id: 120, name: "staryu", types: ["water"], gen: 1 },
  { id: 121, name: "starmie", types: ["water", "psychic"], gen: 1 },
  { id: 122, name: "mr. Mime", types: ["psychic", "fairy"], gen: 1 },
  { id: 123, name: "scyther", types: ["bug", "flying"], gen: 1 },
  { id: 124, name: "jynx", types: ["ice", "psychic"], gen: 1 },
  { id: 125, name: "electabuzz", types: ["electric"], gen: 1 },
  { id: 126, name: "magmar", types: ["fire"], gen: 1 },
  { id: 127, name: "pinsir", types: ["bug"], gen: 1 },
  { id: 128, name: "tauros", types: ["normal"], gen: 1 },
  { id: 129, name: "magikarp", types: ["water"], gen: 1 },
  { id: 130, name: "gyarados", types: ["water", "flying"], gen: 1 },
  { id: 131, name: "lapras", types: ["water", "ice"], gen: 1 },
  { id: 132, name: "ditto", types: ["normal"], gen: 1 },
  { id: 133, name: "eevee", types: ["normal"], gen: 1 },
  { id: 134, name: "vaporeon", types: ["water"], gen: 1 },
  { id: 135, name: "jolteon", types: ["electric"], gen: 1 },
  { id: 136, name: "flareon", types: ["fire"], gen: 1 },
  { id: 137, name: "porygon", types: ["normal"], gen: 1 },
  { id: 138, name: "omanyte", types: ["rock", "water"], gen: 1 },
  { id: 139, name: "omastar", types: ["rock", "water"], gen: 1 },
  { id: 140, name: "kabuto", types: ["rock", "water"], gen: 1 },
  { id: 141, name: "kabutops", types: ["rock", "water"], gen: 1 },
  { id: 142, name: "aerodactyl", types: ["rock", "flying"], gen: 1 },
  { id: 143, name: "snorlax", types: ["normal"], gen: 1 },
  { id: 144, name: "articuno", types: ["ice", "flying"], gen: 1 },
  { id: 145, name: "zapdos", types: ["electric", "flying"], gen: 1 },
  { id: 146, name: "moltres", types: ["fire", "flying"], gen: 1 },
  { id: 147, name: "dratini", types: ["dragon"], gen: 1 },
  { id: 148, name: "dragonair", types: ["dragon"], gen: 1 },
  { id: 149, name: "dragonite", types: ["dragon", "flying"], gen: 1 },
  { id: 150, name: "mewtwo", types: ["psychic"], gen: 1 },
  { id: 151, name: "mew", types: ["psychic"], gen: 1 },
  { id: 152, name: "chikorita", types: ["grass"], gen: 2 },
  { id: 153, name: "bayleef", types: ["grass"], gen: 2 },
  { id: 154, name: "meganium", types: ["grass"], gen: 2 },
  { id: 155, name: "cyndaquil", types: ["fire"], gen: 2 },
  { id: 156, name: "quilava", types: ["fire"], gen: 2 },
  { id: 157, name: "typhlosion", types: ["fire"], gen: 2 },
  { id: 158, name: "totodile", types: ["water"], gen: 2 },
  { id: 159, name: "croconaw", types: ["water"], gen: 2 },
  { id: 160, name: "feraligatr", types: ["water"], gen: 2 },
  { id: 161, name: "sentret", types: ["normal"], gen: 2 },
  { id: 162, name: "furret", types: ["normal"], gen: 2 },
  { id: 163, name: "hoothoot", types: ["normal", "flying"], gen: 2 },
  { id: 164, name: "noctowl", types: ["normal", "flying"], gen: 2 },
  { id: 165, name: "ledyba", types: ["bug", "flying"], gen: 2 },
  { id: 166, name: "ledian", types: ["bug", "flying"], gen: 2 },
  { id: 167, name: "spinarak", types: ["bug", "poison"], gen: 2 },
  { id: 168, name: "ariados", types: ["bug", "poison"], gen: 2 },
  { id: 169, name: "crobat", types: ["poison", "flying"], gen: 2 },
  { id: 170, name: "chinchou", types: ["water", "electric"], gen: 2 },
  { id: 171, name: "lanturn", types: ["water", "electric"], gen: 2 },
  { id: 172, name: "pichu", types: ["electric"], gen: 2 },
  { id: 173, name: "cleffa", types: ["fairy"], gen: 2 },
  { id: 174, name: "igglybuff", types: ["normal", "fairy"], gen: 2 },
  { id: 175, name: "togepi", types: ["fairy"], gen: 2 },
  { id: 176, name: "togetic", types: ["fairy", "flying"], gen: 2 },
  { id: 177, name: "natu", types: ["psychic", "flying"], gen: 2 },
  { id: 178, name: "xatu", types: ["psychic", "flying"], gen: 2 },
  { id: 179, name: "mareep", types: ["electric"], gen: 2 },
  { id: 180, name: "flaaffy", types: ["electric"], gen: 2 },
  { id: 181, name: "ampharos", types: ["electric"], gen: 2 },
  { id: 182, name: "bellossom", types: ["grass"], gen: 2 },
  { id: 183, name: "marill", types: ["water", "fairy"], gen: 2 },
  { id: 184, name: "azumarill", types: ["water", "fairy"], gen: 2 },
  { id: 185, name: "sudowoodo", types: ["rock"], gen: 2 },
  { id: 186, name: "politoed", types: ["water"], gen: 2 },
  { id: 187, name: "hoppip", types: ["grass", "flying"], gen: 2 },
  { id: 188, name: "skiploom", types: ["grass", "flying"], gen: 2 },
  { id: 189, name: "jumpluff", types: ["grass", "flying"], gen: 2 },
  { id: 190, name: "aipom", types: ["normal"], gen: 2 },
  { id: 191, name: "sunkern", types: ["grass"], gen: 2 },
  { id: 192, name: "sunflora", types: ["grass"], gen: 2 },
  { id: 193, name: "yanma", types: ["bug", "flying"], gen: 2 },
  { id: 194, name: "wooper", types: ["water", "ground"], gen: 2 },
  { id: 195, name: "quagsire", types: ["water", "ground"], gen: 2 },
  { id: 196, name: "espeon", types: ["psychic"], gen: 2 },
  { id: 197, name: "umbreon", types: ["dark"], gen: 2 },
  { id: 198, name: "murkrow", types: ["dark", "flying"], gen: 2 },
  { id: 199, name: "slowking", types: ["water", "psychic"], gen: 2 },
  { id: 200, name: "misdreavus", types: ["ghost"], gen: 2 },
  { id: 201, name: "unown", types: ["psychic"], gen: 2 },
  { id: 202, name: "wobbuffet", types: ["psychic"], gen: 2 },
  { id: 203, name: "girafarig", types: ["normal", "psychic"], gen: 2 },
  { id: 204, name: "pineco", types: ["bug"], gen: 2 },
  { id: 205, name: "forretress", types: ["bug", "steel"], gen: 2 },
  { id: 206, name: "dunsparce", types: ["normal"], gen: 2 },
  { id: 207, name: "gligar", types: ["ground", "flying"], gen: 2 },
  { id: 208, name: "steelix", types: ["steel", "ground"], gen: 2 },
  { id: 209, name: "snubbull", types: ["fairy"], gen: 2 },
  { id: 210, name: "granbull", types: ["fairy"], gen: 2 },
  { id: 211, name: "qwilfish", types: ["water", "poison"], gen: 2 },
  { id: 212, name: "scizor", types: ["bug", "steel"], gen: 2 },
  { id: 213, name: "shuckle", types: ["bug", "rock"], gen: 2 },
  { id: 214, name: "heracross", types: ["bug", "fighting"], gen: 2 },
  { id: 215, name: "sneasel", types: ["dark", "ice"], gen: 2 },
  { id: 216, name: "teddiursa", types: ["normal"], gen: 2 },
  { id: 217, name: "ursaring", types: ["normal"], gen: 2 },
  { id: 218, name: "slugma", types: ["fire"], gen: 2 },
  { id: 219, name: "magcargo", types: ["fire", "rock"], gen: 2 },
  { id: 220, name: "swinub", types: ["ice", "ground"], gen: 2 },
  { id: 221, name: "piloswine", types: ["ice", "ground"], gen: 2 },
  { id: 222, name: "corsola", types: ["water", "rock"], gen: 2 },
  { id: 223, name: "remoraid", types: ["water"], gen: 2 },
  { id: 224, name: "octillery", types: ["water"], gen: 2 },
  { id: 225, name: "delibird", types: ["ice", "flying"], gen: 2 },
  { id: 226, name: "mantine", types: ["water", "flying"], gen: 2 },
  { id: 227, name: "skarmory", types: ["steel", "flying"], gen: 2 },
  { id: 228, name: "houndour", types: ["dark", "fire"], gen: 2 },
  { id: 229, name: "houndoom", types: ["dark", "fire"], gen: 2 },
  { id: 230, name: "kingdra", types: ["water", "dragon"], gen: 2 },
  { id: 231, name: "phanpy", types: ["ground"], gen: 2 },
  { id: 232, name: "donphan", types: ["ground"], gen: 2 },
  { id: 233, name: "porygon2", types: ["normal"], gen: 2 },
  { id: 234, name: "stantler", types: ["normal"], gen: 2 },
  { id: 235, name: "smeargle", types: ["normal"], gen: 2 },
  { id: 236, name: "tyrogue", types: ["fighting"], gen: 2 },
  { id: 237, name: "hitmontop", types: ["fighting"], gen: 2 },
  { id: 238, name: "smoochum", types: ["ice", "psychic"], gen: 2 },
  { id: 239, name: "elekid", types: ["electric"], gen: 2 },
  { id: 240, name: "magby", types: ["fire"], gen: 2 },
  { id: 241, name: "miltank", types: ["normal"], gen: 2 },
  { id: 242, name: "blissey", types: ["normal"], gen: 2 },
  { id: 243, name: "raikou", types: ["electric"], gen: 2 },
  { id: 244, name: "entei", types: ["fire"], gen: 2 },
  { id: 245, name: "suicune", types: ["water"], gen: 2 },
  { id: 246, name: "larvitar", types: ["rock", "ground"], gen: 2 },
  { id: 247, name: "pupitar", types: ["rock", "ground"], gen: 2 },
  { id: 248, name: "tyranitar", types: ["rock", "dark"], gen: 2 },
  { id: 249, name: "lugia", types: ["psychic", "flying"], gen: 2 },
  { id: 250, name: "ho-Oh", types: ["fire", "flying"], gen: 2 },
  { id: 251, name: "celebi", types: ["psychic", "grass"], gen: 2 },
  { id: 252, name: "treecko", types: ["grass"], gen: 3 },
  { id: 253, name: "grovyle", types: ["grass"], gen: 3 },
  { id: 254, name: "sceptile", types: ["grass"], gen: 3 },
  { id: 255, name: "torchic", types: ["fire"], gen: 3 },
  { id: 256, name: "combusken", types: ["fire", "fighting"], gen: 3 },
  { id: 257, name: "blaziken", types: ["fire", "fighting"], gen: 3 },
  { id: 258, name: "mudkip", types: ["water"], gen: 3 },
  { id: 259, name: "marshtomp", types: ["water", "ground"], gen: 3 },
  { id: 260, name: "swampert", types: ["water", "ground"], gen: 3 },
  { id: 261, name: "poochyena", types: ["dark"], gen: 3 },
  { id: 262, name: "mightyena", types: ["dark"], gen: 3 },
  { id: 263, name: "zigzagoon", types: ["normal"], gen: 3 },
  { id: 264, name: "linoone", types: ["normal"], gen: 3 },
  { id: 265, name: "wurmple", types: ["bug"], gen: 3 },
  { id: 266, name: "silcoon", types: ["bug"], gen: 3 },
  { id: 267, name: "beautifly", types: ["bug", "flying"], gen: 3 },
  { id: 268, name: "cascoon", types: ["bug"], gen: 3 },
  { id: 269, name: "dustox", types: ["bug", "poison"], gen: 3 },
  { id: 270, name: "lotad", types: ["water", "grass"], gen: 3 },
  { id: 271, name: "lombre", types: ["water", "grass"], gen: 3 },
  { id: 272, name: "ludicolo", types: ["water", "grass"], gen: 3 },
  { id: 273, name: "seedot", types: ["grass"], gen: 3 },
  { id: 274, name: "nuzleaf", types: ["grass", "dark"], gen: 3 },
  { id: 275, name: "shiftry", types: ["grass", "dark"], gen: 3 },
  { id: 276, name: "taillow", types: ["normal", "flying"], gen: 3 },
  { id: 277, name: "swellow", types: ["normal", "flying"], gen: 3 },
  { id: 278, name: "wingull", types: ["water", "flying"], gen: 3 },
  { id: 279, name: "pelipper", types: ["water", "flying"], gen: 3 },
  { id: 280, name: "ralts", types: ["psychic", "fairy"], gen: 3 },
  { id: 281, name: "kirlia", types: ["psychic", "fairy"], gen: 3 },
  { id: 282, name: "gardevoir", types: ["psychic", "fairy"], gen: 3 },
  { id: 283, name: "surskit", types: ["bug", "water"], gen: 3 },
  { id: 284, name: "masquerain", types: ["bug", "flying"], gen: 3 },
  { id: 285, name: "shroomish", types: ["grass"], gen: 3 },
  { id: 286, name: "breloom", types: ["grass", "fighting"], gen: 3 },
  { id: 287, name: "slakoth", types: ["normal"], gen: 3 },
  { id: 288, name: "vigoroth", types: ["normal"], gen: 3 },
  { id: 289, name: "slaking", types: ["normal"], gen: 3 },
  { id: 290, name: "nincada", types: ["bug", "ground"], gen: 3 },
  { id: 291, name: "ninjask", types: ["bug", "flying"], gen: 3 },
  { id: 292, name: "shedinja", types: ["bug", "ghost"], gen: 3 },
  { id: 293, name: "whismur", types: ["normal"], gen: 3 },
  { id: 294, name: "loudred", types: ["normal"], gen: 3 },
  { id: 295, name: "exploud", types: ["normal"], gen: 3 },
  { id: 296, name: "makuhita", types: ["fighting"], gen: 3 },
  { id: 297, name: "hariyama", types: ["fighting"], gen: 3 },
  { id: 298, name: "azurill", types: ["normal", "fairy"], gen: 3 },
  { id: 299, name: "nosepass", types: ["rock"], gen: 3 },
  { id: 300, name: "skitty", types: ["normal"], gen: 3 },
  { id: 301, name: "delcatty", types: ["normal"], gen: 3 },
  { id: 302, name: "sableye", types: ["dark", "ghost"], gen: 3 },
  { id: 303, name: "mawile", types: ["steel", "fairy"], gen: 3 },
  { id: 304, name: "aron", types: ["steel", "rock"], gen: 3 },
  { id: 305, name: "lairon", types: ["steel", "rock"], gen: 3 },
  { id: 306, name: "aggron", types: ["steel", "rock"], gen: 3 },
  { id: 307, name: "meditite", types: ["fighting", "psychic"], gen: 3 },
  { id: 308, name: "medicham", types: ["fighting", "psychic"], gen: 3 },
  { id: 309, name: "electrike", types: ["electric"], gen: 3 },
  { id: 310, name: "manectric", types: ["electric"], gen: 3 },
  { id: 311, name: "plusle", types: ["electric"], gen: 3 },
  { id: 312, name: "minun", types: ["electric"], gen: 3 },
  { id: 313, name: "volbeat", types: ["bug"], gen: 3 },
  { id: 314, name: "illumise", types: ["bug"], gen: 3 },
  { id: 315, name: "roselia", types: ["grass", "poison"], gen: 3 },
  { id: 316, name: "gulpin", types: ["poison"], gen: 3 },
  { id: 317, name: "swalot", types: ["poison"], gen: 3 },
  { id: 318, name: "carvanha", types: ["water", "dark"], gen: 3 },
  { id: 319, name: "sharpedo", types: ["water", "dark"], gen: 3 },
  { id: 320, name: "wailmer", types: ["water"], gen: 3 },
  { id: 321, name: "wailord", types: ["water"], gen: 3 },
  { id: 322, name: "numel", types: ["fire", "ground"], gen: 3 },
  { id: 323, name: "camerupt", types: ["fire", "ground"], gen: 3 },
  { id: 324, name: "torkoal", types: ["fire"], gen: 3 },
  { id: 325, name: "spoink", types: ["psychic"], gen: 3 },
  { id: 326, name: "grumpig", types: ["psychic"], gen: 3 },
  { id: 327, name: "spinda", types: ["normal"], gen: 3 },
  { id: 328, name: "trapinch", types: ["ground"], gen: 3 },
  { id: 329, name: "vibrava", types: ["ground", "dragon"], gen: 3 },
  { id: 330, name: "flygon", types: ["ground", "dragon"], gen: 3 },
  { id: 331, name: "cacnea", types: ["grass"], gen: 3 },
  { id: 332, name: "cacturne", types: ["grass", "dark"], gen: 3 },
  { id: 333, name: "swablu", types: ["normal", "flying"], gen: 3 },
  { id: 334, name: "altaria", types: ["dragon", "flying"], gen: 3 },
  { id: 335, name: "zangoose", types: ["normal"], gen: 3 },
  { id: 336, name: "seviper", types: ["poison"], gen: 3 },
  { id: 337, name: "lunatone", types: ["rock", "psychic"], gen: 3 },
  { id: 338, name: "solrock", types: ["rock", "psychic"], gen: 3 },
  { id: 339, name: "barboach", types: ["water", "ground"], gen: 3 },
  { id: 340, name: "whiscash", types: ["water", "ground"], gen: 3 },
  { id: 341, name: "corphish", types: ["water"], gen: 3 },
  { id: 342, name: "crawdaunt", types: ["water", "dark"], gen: 3 },
  { id: 343, name: "baltoy", types: ["ground", "psychic"], gen: 3 },
  { id: 344, name: "claydol", types: ["ground", "psychic"], gen: 3 },
  { id: 345, name: "lileep", types: ["rock", "grass"], gen: 3 },
  { id: 346, name: "cradily", types: ["rock", "grass"], gen: 3 },
  { id: 347, name: "anorith", types: ["rock", "bug"], gen: 3 },
  { id: 348, name: "armaldo", types: ["rock", "bug"], gen: 3 },
  { id: 349, name: "feebas", types: ["water"], gen: 3 },
  { id: 350, name: "milotic", types: ["water"], gen: 3 },
  { id: 351, name: "castform", types: ["normal"], gen: 3 },
  { id: 352, name: "kecleon", types: ["normal"], gen: 3 },
  { id: 353, name: "shuppet", types: ["ghost"], gen: 3 },
  { id: 354, name: "banette", types: ["ghost"], gen: 3 },
  { id: 355, name: "duskull", types: ["ghost"], gen: 3 },
  { id: 356, name: "dusclops", types: ["ghost"], gen: 3 },
  { id: 357, name: "tropius", types: ["grass", "flying"], gen: 3 },
  { id: 358, name: "chimecho", types: ["psychic"], gen: 3 },
  { id: 359, name: "absol", types: ["dark"], gen: 3 },
  { id: 360, name: "wynaut", types: ["psychic"], gen: 3 },
  { id: 361, name: "snorunt", types: ["ice"], gen: 3 },
  { id: 362, name: "glalie", types: ["ice"], gen: 3 },
  { id: 363, name: "spheal", types: ["ice", "water"], gen: 3 },
  { id: 364, name: "sealeo", types: ["ice", "water"], gen: 3 },
  { id: 365, name: "walrein", types: ["ice", "water"], gen: 3 },
  { id: 366, name: "clamperl", types: ["water"], gen: 3 },
  { id: 367, name: "huntail", types: ["water"], gen: 3 },
  { id: 368, name: "gorebyss", types: ["water"], gen: 3 },
  { id: 369, name: "relicanth", types: ["water", "rock"], gen: 3 },
  { id: 370, name: "luvdisc", types: ["water"], gen: 3 },
  { id: 371, name: "bagon", types: ["dragon"], gen: 3 },
  { id: 372, name: "shelgon", types: ["dragon"], gen: 3 },
  { id: 373, name: "salamence", types: ["dragon", "flying"], gen: 3 },
  { id: 374, name: "beldum", types: ["steel", "psychic"], gen: 3 },
  { id: 375, name: "metang", types: ["steel", "psychic"], gen: 3 },
  { id: 376, name: "metagross", types: ["steel", "psychic"], gen: 3 },
  { id: 377, name: "regirock", types: ["rock"], gen: 3 },
  { id: 378, name: "regice", types: ["ice"], gen: 3 },
  { id: 379, name: "registeel", types: ["steel"], gen: 3 },
  { id: 380, name: "latias", types: ["dragon", "psychic"], gen: 3 },
  { id: 381, name: "latios", types: ["dragon", "psychic"], gen: 3 },
  { id: 382, name: "kyogre", types: ["water"], gen: 3 },
  { id: 383, name: "groudon", types: ["ground"], gen: 3 },
  { id: 384, name: "rayquaza", types: ["dragon", "flying"], gen: 3 },
  { id: 385, name: "jirachi", types: ["steel", "psychic"], gen: 3 },
  { id: 386, name: "deoxys", types: ["psychic"], gen: 3 },
  { id: 387, name: "turtwig", types: ["grass"], gen: 4 },
  { id: 388, name: "grotle", types: ["grass"], gen: 4 },
  { id: 389, name: "torterra", types: ["grass", "ground"], gen: 4 },
  { id: 390, name: "chimchar", types: ["fire"], gen: 4 },
  { id: 391, name: "monferno", types: ["fire", "fighting"], gen: 4 },
  { id: 392, name: "infernape", types: ["fire", "fighting"], gen: 4 },
  { id: 393, name: "piplup", types: ["water"], gen: 4 },
  { id: 394, name: "prinplup", types: ["water"], gen: 4 },
  { id: 395, name: "empoleon", types: ["water", "steel"], gen: 4 },
  { id: 396, name: "starly", types: ["normal", "flying"], gen: 4 },
  { id: 397, name: "staravia", types: ["normal", "flying"], gen: 4 },
  { id: 398, name: "staraptor", types: ["normal", "flying"], gen: 4 },
  { id: 399, name: "bidoof", types: ["normal"], gen: 4 },
  { id: 400, name: "bibarel", types: ["normal", "water"], gen: 4 },
  { id: 401, name: "kricketot", types: ["bug"], gen: 4 },
  { id: 402, name: "kricketune", types: ["bug"], gen: 4 },
  { id: 403, name: "shinx", types: ["electric"], gen: 4 },
  { id: 404, name: "luxio", types: ["electric"], gen: 4 },
  { id: 405, name: "luxray", types: ["electric"], gen: 4 },
  { id: 406, name: "budew", types: ["grass", "poison"], gen: 4 },
  { id: 407, name: "roserade", types: ["grass", "poison"], gen: 4 },
  { id: 408, name: "cranidos", types: ["rock"], gen: 4 },
  { id: 409, name: "rampardos", types: ["rock"], gen: 4 },
  { id: 410, name: "shieldon", types: ["rock", "steel"], gen: 4 },
  { id: 411, name: "bastiodon", types: ["rock", "steel"], gen: 4 },
  { id: 412, name: "burmy", types: ["bug"], gen: 4 },
  { id: 413, name: "wormadam", types: ["bug", "grass"], gen: 4 },
  { id: 414, name: "mothim", types: ["bug", "flying"], gen: 4 },
  { id: 415, name: "combee", types: ["bug", "flying"], gen: 4 },
  { id: 416, name: "vespiquen", types: ["bug", "flying"], gen: 4 },
  { id: 417, name: "pachirisu", types: ["electric"], gen: 4 },
  { id: 418, name: "buizel", types: ["water"], gen: 4 },
  { id: 419, name: "floatzel", types: ["water"], gen: 4 },
  { id: 420, name: "cherubi", types: ["grass"], gen: 4 },
  { id: 421, name: "cherrim", types: ["grass"], gen: 4 },
  { id: 422, name: "shellos", types: ["water"], gen: 4 },
  { id: 423, name: "gastrodon", types: ["water", "ground"], gen: 4 },
  { id: 424, name: "ambipom", types: ["normal"], gen: 4 },
  { id: 425, name: "drifloon", types: ["ghost", "flying"], gen: 4 },
  { id: 426, name: "drifblim", types: ["ghost", "flying"], gen: 4 },
  { id: 427, name: "buneary", types: ["normal"], gen: 4 },
  { id: 428, name: "lopunny", types: ["normal"], gen: 4 },
  { id: 429, name: "mismagius", types: ["ghost"], gen: 4 },
  { id: 430, name: "honchkrow", types: ["dark", "flying"], gen: 4 },
  { id: 431, name: "glameow", types: ["normal"], gen: 4 },
  { id: 432, name: "purugly", types: ["normal"], gen: 4 },
  { id: 433, name: "chingling", types: ["psychic"], gen: 4 },
  { id: 434, name: "stunky", types: ["poison", "dark"], gen: 4 },
  { id: 435, name: "skuntank", types: ["poison", "dark"], gen: 4 },
  { id: 436, name: "bronzor", types: ["steel", "psychic"], gen: 4 },
  { id: 437, name: "bronzong", types: ["steel", "psychic"], gen: 4 },
  { id: 438, name: "bonsly", types: ["rock"], gen: 4 },
  { id: 439, name: "mime Jr.", types: ["psychic", "fairy"], gen: 4 },
  { id: 440, name: "happiny", types: ["normal"], gen: 4 },
  { id: 441, name: "chatot", types: ["normal", "flying"], gen: 4 },
  { id: 442, name: "spiritomb", types: ["ghost", "dark"], gen: 4 },
  { id: 443, name: "gible", types: ["dragon", "ground"], gen: 4 },
  { id: 444, name: "gabite", types: ["dragon", "ground"], gen: 4 },
  { id: 445, name: "garchomp", types: ["dragon", "ground"], gen: 4 },
  { id: 446, name: "munchlax", types: ["normal"], gen: 4 },
  { id: 447, name: "riolu", types: ["fighting"], gen: 4 },
  { id: 448, name: "lucario", types: ["fighting", "steel"], gen: 4 },
  { id: 449, name: "hippopotas", types: ["ground"], gen: 4 },
  { id: 450, name: "hippowdon", types: ["ground"], gen: 4 },
  { id: 451, name: "skorupi", types: ["poison", "bug"], gen: 4 },
  { id: 452, name: "drapion", types: ["poison", "dark"], gen: 4 },
  { id: 453, name: "croagunk", types: ["poison", "fighting"], gen: 4 },
  { id: 454, name: "toxicroak", types: ["poison", "fighting"], gen: 4 },
  { id: 455, name: "carnivine", types: ["grass"], gen: 4 },
  { id: 456, name: "finneon", types: ["water"], gen: 4 },
  { id: 457, name: "lumineon", types: ["water"], gen: 4 },
  { id: 458, name: "mantyke", types: ["water", "flying"], gen: 4 },
  { id: 459, name: "snover", types: ["grass", "ice"], gen: 4 },
  { id: 460, name: "abomasnow", types: ["grass", "ice"], gen: 4 },
  { id: 461, name: "weavile", types: ["dark", "ice"], gen: 4 },
  { id: 462, name: "magnezone", types: ["electric", "steel"], gen: 4 },
  { id: 463, name: "lickilicky", types: ["normal"], gen: 4 },
  { id: 464, name: "rhyperior", types: ["ground", "rock"], gen: 4 },
  { id: 465, name: "tangrowth", types: ["grass"], gen: 4 },
  { id: 466, name: "electivire", types: ["electric"], gen: 4 },
  { id: 467, name: "magmortar", types: ["fire"], gen: 4 },
  { id: 468, name: "togekiss", types: ["fairy", "flying"], gen: 4 },
  { id: 469, name: "yanmega", types: ["bug", "flying"], gen: 4 },
  { id: 470, name: "leafeon", types: ["grass"], gen: 4 },
  { id: 471, name: "glaceon", types: ["ice"], gen: 4 },
  { id: 472, name: "gliscor", types: ["ground", "flying"], gen: 4 },
  { id: 473, name: "mamoswine", types: ["ice", "ground"], gen: 4 },
  { id: 474, name: "porygon-Z", types: ["normal"], gen: 4 },
  { id: 475, name: "gallade", types: ["psychic", "fighting"], gen: 4 },
  { id: 476, name: "probopass", types: ["rock", "steel"], gen: 4 },
  { id: 477, name: "dusknoir", types: ["ghost"], gen: 4 },
  { id: 478, name: "froslass", types: ["ice", "ghost"], gen: 4 },
  { id: 479, name: "rotom", types: ["electric", "ghost"], gen: 4 },
  { id: 480, name: "uxie", types: ["psychic"], gen: 4 },
  { id: 481, name: "mesprit", types: ["psychic"], gen: 4 },
  { id: 482, name: "azelf", types: ["psychic"], gen: 4 },
  { id: 483, name: "dialga", types: ["steel", "dragon"], gen: 4 },
  { id: 484, name: "palkia", types: ["water", "dragon"], gen: 4 },
  { id: 485, name: "heatran", types: ["fire", "steel"], gen: 4 },
  { id: 486, name: "regigigas", types: ["normal"], gen: 4 },
  { id: 487, name: "giratina", types: ["ghost", "dragon"], gen: 4 },
  { id: 488, name: "cresselia", types: ["psychic"], gen: 4 },
  { id: 489, name: "phione", types: ["water"], gen: 4 },
  { id: 490, name: "manaphy", types: ["water"], gen: 4 },
  { id: 491, name: "darkrai", types: ["dark"], gen: 4 },
  { id: 492, name: "shaymin", types: ["grass"], gen: 4 },
  { id: 493, name: "arceus", types: ["normal"], gen: 4 },
  { id: 494, name: "victini", types: ["psychic", "fire"], gen: 5 },
  { id: 495, name: "snivy", types: ["grass"], gen: 5 },
  { id: 496, name: "servine", types: ["grass"], gen: 5 },
  { id: 497, name: "serperior", types: ["grass"], gen: 5 },
  { id: 498, name: "tepig", types: ["fire"], gen: 5 },
  { id: 499, name: "pignite", types: ["fire", "fighting"], gen: 5 },
  { id: 500, name: "emboar", types: ["fire", "fighting"], gen: 5 },
  { id: 501, name: "oshawott", types: ["water"], gen: 5 },
  { id: 502, name: "dewott", types: ["water"], gen: 5 },
  { id: 503, name: "samurott", types: ["water"], gen: 5 },
  { id: 504, name: "patrat", types: ["normal"], gen: 5 },
  { id: 505, name: "watchog", types: ["normal"], gen: 5 },
  { id: 506, name: "lillipup", types: ["normal"], gen: 5 },
  { id: 507, name: "herdier", types: ["normal"], gen: 5 },
  { id: 508, name: "stoutland", types: ["normal"], gen: 5 },
  { id: 509, name: "purrloin", types: ["dark"], gen: 5 },
  { id: 510, name: "liepard", types: ["dark"], gen: 5 },
  { id: 511, name: "pansage", types: ["grass"], gen: 5 },
  { id: 512, name: "simisage", types: ["grass"], gen: 5 },
  { id: 513, name: "pansear", types: ["fire"], gen: 5 },
  { id: 514, name: "simisear", types: ["fire"], gen: 5 },
  { id: 515, name: "panpour", types: ["water"], gen: 5 },
  { id: 516, name: "simipour", types: ["water"], gen: 5 },
  { id: 517, name: "munna", types: ["psychic"], gen: 5 },
  { id: 518, name: "musharna", types: ["psychic"], gen: 5 },
  { id: 519, name: "pidove", types: ["normal", "flying"], gen: 5 },
  { id: 520, name: "tranquill", types: ["normal", "flying"], gen: 5 },
  { id: 521, name: "unfezant", types: ["normal", "flying"], gen: 5 },
  { id: 522, name: "blitzle", types: ["electric"], gen: 5 },
  { id: 523, name: "zebstrika", types: ["electric"], gen: 5 },
  { id: 524, name: "roggenrola", types: ["rock"], gen: 5 },
  { id: 525, name: "boldore", types: ["rock"], gen: 5 },
  { id: 526, name: "gigalith", types: ["rock"], gen: 5 },
  { id: 527, name: "woobat", types: ["psychic", "flying"], gen: 5 },
  { id: 528, name: "swoobat", types: ["psychic", "flying"], gen: 5 },
  { id: 529, name: "drilbur", types: ["ground"], gen: 5 },
  { id: 530, name: "excadrill", types: ["ground", "steel"], gen: 5 },
  { id: 531, name: "audino", types: ["normal"], gen: 5 },
  { id: 532, name: "timburr", types: ["fighting"], gen: 5 },
  { id: 533, name: "gurdurr", types: ["fighting"], gen: 5 },
  { id: 534, name: "conkeldurr", types: ["fighting"], gen: 5 },
  { id: 535, name: "tympole", types: ["water"], gen: 5 },
  { id: 536, name: "palpitoad", types: ["water", "ground"], gen: 5 },
  { id: 537, name: "seismitoad", types: ["water", "ground"], gen: 5 },
  { id: 538, name: "throh", types: ["fighting"], gen: 5 },
  { id: 539, name: "sawk", types: ["fighting"], gen: 5 },
  { id: 540, name: "sewaddle", types: ["bug", "grass"], gen: 5 },
  { id: 541, name: "swadloon", types: ["bug", "grass"], gen: 5 },
  { id: 542, name: "leavanny", types: ["bug", "grass"], gen: 5 },
  { id: 543, name: "venipede", types: ["bug", "poison"], gen: 5 },
  { id: 544, name: "whirlipede", types: ["bug", "poison"], gen: 5 },
  { id: 545, name: "scolipede", types: ["bug", "poison"], gen: 5 },
  { id: 546, name: "cottonee", types: ["grass", "fairy"], gen: 5 },
  { id: 547, name: "whimsicott", types: ["grass", "fairy"], gen: 5 },
  { id: 548, name: "petilil", types: ["grass"], gen: 5 },
  { id: 549, name: "lilligant", types: ["grass"], gen: 5 },
  { id: 550, name: "basculin", types: ["water"], gen: 5 },
  { id: 551, name: "sandile", types: ["ground", "dark"], gen: 5 },
  { id: 552, name: "krokorok", types: ["ground", "dark"], gen: 5 },
  { id: 553, name: "krookodile", types: ["ground", "dark"], gen: 5 },
  { id: 554, name: "darumaka", types: ["fire"], gen: 5 },
  { id: 555, name: "darmanitan", types: ["fire"], gen: 5 },
  { id: 556, name: "maractus", types: ["grass"], gen: 5 },
  { id: 557, name: "dwebble", types: ["bug", "rock"], gen: 5 },
  { id: 558, name: "crustle", types: ["bug", "rock"], gen: 5 },
  { id: 559, name: "scraggy", types: ["dark", "fighting"], gen: 5 },
  { id: 560, name: "scrafty", types: ["dark", "fighting"], gen: 5 },
  { id: 561, name: "sigilyph", types: ["psychic", "flying"], gen: 5 },
  { id: 562, name: "yamask", types: ["ghost"], gen: 5 },
  { id: 563, name: "cofagrigus", types: ["ghost"], gen: 5 },
  { id: 564, name: "tirtouga", types: ["water", "rock"], gen: 5 },
  { id: 565, name: "carracosta", types: ["water", "rock"], gen: 5 },
  { id: 566, name: "archen", types: ["rock", "flying"], gen: 5 },
  { id: 567, name: "archeops", types: ["rock", "flying"], gen: 5 },
  { id: 568, name: "trubbish", types: ["poison"], gen: 5 },
  { id: 569, name: "garbodor", types: ["poison"], gen: 5 },
  { id: 570, name: "zorua", types: ["dark"], gen: 5 },
  { id: 571, name: "zoroark", types: ["dark"], gen: 5 },
  { id: 572, name: "minccino", types: ["normal"], gen: 5 },
  { id: 573, name: "cinccino", types: ["normal"], gen: 5 },
  { id: 574, name: "gothita", types: ["psychic"], gen: 5 },
  { id: 575, name: "gothorita", types: ["psychic"], gen: 5 },
  { id: 576, name: "gothitelle", types: ["psychic"], gen: 5 },
  { id: 577, name: "solosis", types: ["psychic"], gen: 5 },
  { id: 578, name: "duosion", types: ["psychic"], gen: 5 },
  { id: 579, name: "reuniclus", types: ["psychic"], gen: 5 },
  { id: 580, name: "ducklett", types: ["water", "flying"], gen: 5 },
  { id: 581, name: "swanna", types: ["water", "flying"], gen: 5 },
  { id: 582, name: "vanillite", types: ["ice"], gen: 5 },
  { id: 583, name: "vanillish", types: ["ice"], gen: 5 },
  { id: 584, name: "vanilluxe", types: ["ice"], gen: 5 },
  { id: 585, name: "deerling", types: ["normal", "grass"], gen: 5 },
  { id: 586, name: "sawsbuck", types: ["normal", "grass"], gen: 5 },
  { id: 587, name: "emolga", types: ["electric", "flying"], gen: 5 },
  { id: 588, name: "karrablast", types: ["bug"], gen: 5 },
  { id: 589, name: "escavalier", types: ["bug", "steel"], gen: 5 },
  { id: 590, name: "foongus", types: ["grass", "poison"], gen: 5 },
  { id: 591, name: "amoonguss", types: ["grass", "poison"], gen: 5 },
  { id: 592, name: "frillish", types: ["water", "ghost"], gen: 5 },
  { id: 593, name: "jellicent", types: ["water", "ghost"], gen: 5 },
  { id: 594, name: "alomomola", types: ["water"], gen: 5 },
  { id: 595, name: "joltik", types: ["bug", "electric"], gen: 5 },
  { id: 596, name: "galvantula", types: ["bug", "electric"], gen: 5 },
  { id: 597, name: "ferroseed", types: ["grass", "steel"], gen: 5 },
  { id: 598, name: "ferrothorn", types: ["grass", "steel"], gen: 5 },
  { id: 599, name: "klink", types: ["steel"], gen: 5 },
  { id: 600, name: "klang", types: ["steel"], gen: 5 },
  { id: 601, name: "klinklang", types: ["steel"], gen: 5 },
  { id: 602, name: "tynamo", types: ["electric"], gen: 5 },
  { id: 603, name: "eelektrik", types: ["electric"], gen: 5 },
  { id: 604, name: "eelektross", types: ["electric"], gen: 5 },
  { id: 605, name: "elgyem", types: ["psychic"], gen: 5 },
  { id: 606, name: "beheeyem", types: ["psychic"], gen: 5 },
  { id: 607, name: "litwick", types: ["ghost", "fire"], gen: 5 },
  { id: 608, name: "lampent", types: ["ghost", "fire"], gen: 5 },
  { id: 609, name: "chandelure", types: ["ghost", "fire"], gen: 5 },
  { id: 610, name: "axew", types: ["dragon"], gen: 5 },
  { id: 611, name: "fraxure", types: ["dragon"], gen: 5 },
  { id: 612, name: "haxorus", types: ["dragon"], gen: 5 },
  { id: 613, name: "cubchoo", types: ["ice"], gen: 5 },
  { id: 614, name: "beartic", types: ["ice"], gen: 5 },
  { id: 615, name: "cryogonal", types: ["ice"], gen: 5 },
  { id: 616, name: "shelmet", types: ["bug"], gen: 5 },
  { id: 617, name: "accelgor", types: ["bug"], gen: 5 },
  { id: 618, name: "stunfisk", types: ["ground", "electric"], gen: 5 },
  { id: 619, name: "mienfoo", types: ["fighting"], gen: 5 },
  { id: 620, name: "mienshao", types: ["fighting"], gen: 5 },
  { id: 621, name: "druddigon", types: ["dragon"], gen: 5 },
  { id: 622, name: "golett", types: ["ground", "ghost"], gen: 5 },
  { id: 623, name: "golurk", types: ["ground", "ghost"], gen: 5 },
  { id: 624, name: "pawniard", types: ["dark", "steel"], gen: 5 },
  { id: 625, name: "bisharp", types: ["dark", "steel"], gen: 5 },
  { id: 626, name: "bouffalant", types: ["normal"], gen: 5 },
  { id: 627, name: "rufflet", types: ["normal", "flying"], gen: 5 },
  { id: 628, name: "braviary", types: ["normal", "flying"], gen: 5 },
  { id: 629, name: "vullaby", types: ["dark", "flying"], gen: 5 },
  { id: 630, name: "mandibuzz", types: ["dark", "flying"], gen: 5 },
  { id: 631, name: "heatmor", types: ["fire"], gen: 5 },
  { id: 632, name: "durant", types: ["bug", "steel"], gen: 5 },
  { id: 633, name: "deino", types: ["dark", "dragon"], gen: 5 },
  { id: 634, name: "zweilous", types: ["dark", "dragon"], gen: 5 },
  { id: 635, name: "hydreigon", types: ["dark", "dragon"], gen: 5 },
  { id: 636, name: "larvesta", types: ["bug", "fire"], gen: 5 },
  { id: 637, name: "volcarona", types: ["bug", "fire"], gen: 5 },
  { id: 638, name: "cobalion", types: ["steel", "fighting"], gen: 5 },
  { id: 639, name: "terrakion", types: ["rock", "fighting"], gen: 5 },
  { id: 640, name: "virizion", types: ["grass", "fighting"], gen: 5 },
  { id: 641, name: "tornadus", types: ["flying"], gen: 5 },
  { id: 642, name: "thundurus", types: ["electric", "flying"], gen: 5 },
  { id: 643, name: "reshiram", types: ["dragon", "fire"], gen: 5 },
  { id: 644, name: "zekrom", types: ["dragon", "electric"], gen: 5 },
  { id: 645, name: "landorus", types: ["ground", "flying"], gen: 5 },
  { id: 646, name: "kyurem", types: ["dragon", "ice"], gen: 5 },
  { id: 647, name: "keldeo", types: ["water", "fighting"], gen: 5 },
  { id: 648, name: "meloetta", types: ["normal", "psychic"], gen: 5 },
  { id: 649, name: "genesect", types: ["bug", "steel"], gen: 5 },
  { id: 650, name: "chespin", types: ["grass"], gen: 6 },
  { id: 651, name: "quilladin", types: ["grass"], gen: 6 },
  { id: 652, name: "chesnaught", types: ["grass", "fighting"], gen: 6 },
  { id: 653, name: "fennekin", types: ["fire"], gen: 6 },
  { id: 654, name: "braixen", types: ["fire"], gen: 6 },
  { id: 655, name: "delphox", types: ["fire", "psychic"], gen: 6 },
  { id: 656, name: "froakie", types: ["water"], gen: 6 },
  { id: 657, name: "frogadier", types: ["water"], gen: 6 },
  { id: 658, name: "greninja", types: ["water", "dark"], gen: 6 },
  { id: 659, name: "bunnelby", types: ["normal"], gen: 6 },
  { id: 660, name: "diggersby", types: ["normal", "ground"], gen: 6 },
  { id: 661, name: "fletchling", types: ["normal", "flying"], gen: 6 },
  { id: 662, name: "fletchinder", types: ["fire", "flying"], gen: 6 },
  { id: 663, name: "talonflame", types: ["fire", "flying"], gen: 6 },
  { id: 664, name: "scatterbug", types: ["bug"], gen: 6 },
  { id: 665, name: "spewpa", types: ["bug"], gen: 6 },
  { id: 666, name: "vivillon", types: ["bug", "flying"], gen: 6 },
  { id: 667, name: "litleo", types: ["fire", "normal"], gen: 6 },
  { id: 668, name: "pyroar", types: ["fire", "normal"], gen: 6 },
  { id: 669, name: "flabebe", types: ["fairy"], gen: 6 },
  { id: 670, name: "floette", types: ["fairy"], gen: 6 },
  { id: 671, name: "florges", types: ["fairy"], gen: 6 },
  { id: 672, name: "skiddo", types: ["grass"], gen: 6 },
  { id: 673, name: "gogoat", types: ["grass"], gen: 6 },
  { id: 674, name: "pancham", types: ["fighting"], gen: 6 },
  { id: 675, name: "pangoro", types: ["fighting", "dark"], gen: 6 },
  { id: 676, name: "furfrou", types: ["normal"], gen: 6 },
  { id: 677, name: "espurr", types: ["psychic"], gen: 6 },
  { id: 678, name: "meowstic", types: ["psychic"], gen: 6 },
  { id: 679, name: "honedge", types: ["steel", "ghost"], gen: 6 },
  { id: 680, name: "doublade", types: ["steel", "ghost"], gen: 6 },
  { id: 681, name: "aegislash", types: ["steel", "ghost"], gen: 6 },
  { id: 682, name: "spritzee", types: ["fairy"], gen: 6 },
  { id: 683, name: "aromatisse", types: ["fairy"], gen: 6 },
  { id: 684, name: "swirlix", types: ["fairy"], gen: 6 },
  { id: 685, name: "slurpuff", types: ["fairy"], gen: 6 },
  { id: 686, name: "inkay", types: ["dark", "psychic"], gen: 6 },
  { id: 687, name: "malamar", types: ["dark", "psychic"], gen: 6 },
  { id: 688, name: "binacle", types: ["rock", "water"], gen: 6 },
  { id: 689, name: "barbaracle", types: ["rock", "water"], gen: 6 },
  { id: 690, name: "skrelp", types: ["poison", "water"], gen: 6 },
  { id: 691, name: "dragalge", types: ["poison", "dragon"], gen: 6 },
  { id: 692, name: "clauncher", types: ["water"], gen: 6 },
  { id: 693, name: "clawitzer", types: ["water"], gen: 6 },
  { id: 694, name: "helioptile", types: ["electric", "normal"], gen: 6 },
  { id: 695, name: "heliolisk", types: ["electric", "normal"], gen: 6 },
  { id: 696, name: "tyrunt", types: ["rock", "dragon"], gen: 6 },
  { id: 697, name: "tyrantrum", types: ["rock", "dragon"], gen: 6 },
  { id: 698, name: "amaura", types: ["rock", "ice"], gen: 6 },
  { id: 699, name: "aurorus", types: ["rock", "ice"], gen: 6 },
  { id: 700, name: "sylveon", types: ["fairy"], gen: 6 },
  { id: 701, name: "hawlucha", types: ["fighting", "flying"], gen: 6 },
  { id: 702, name: "dedenne", types: ["electric", "fairy"], gen: 6 },
  { id: 703, name: "carbink", types: ["rock", "fairy"], gen: 6 },
  { id: 704, name: "goomy", types: ["dragon"], gen: 6 },
  { id: 705, name: "sliggoo", types: ["dragon"], gen: 6 },
  { id: 706, name: "goodra", types: ["dragon"], gen: 6 },
  { id: 707, name: "klefki", types: ["steel", "fairy"], gen: 6 },
  { id: 708, name: "phantump", types: ["ghost", "grass"], gen: 6 },
  { id: 709, name: "trevenant", types: ["ghost", "grass"], gen: 6 },
  { id: 710, name: "pumpkaboo", types: ["ghost", "grass"], gen: 6 },
  { id: 711, name: "gourgeist", types: ["ghost", "grass"], gen: 6 },
  { id: 712, name: "bergmite", types: ["ice"], gen: 6 },
  { id: 713, name: "avalugg", types: ["ice"], gen: 6 },
  { id: 714, name: "noibat", types: ["flying", "dragon"], gen: 6 },
  { id: 715, name: "noivern", types: ["flying", "dragon"], gen: 6 },
  { id: 716, name: "xerneas", types: ["fairy"], gen: 6 },
  { id: 717, name: "yveltal", types: ["dark", "flying"], gen: 6 },
  { id: 718, name: "zygarde", types: ["dragon", "ground"], gen: 6 },
  { id: 719, name: "diancie", types: ["rock", "fairy"], gen: 6 },
  { id: 720, name: "hoopa", types: ["psychic", "ghost"], gen: 6 },
  { id: 721, name: "volcanion", types: ["fire", "water"], gen: 6 },
  { id: 722, name: "rowlet", types: ["grass", "flying"], gen: 7 },
  { id: 723, name: "dartrix", types: ["grass", "flying"], gen: 7 },
  { id: 724, name: "decidueye", types: ["grass", "ghost"], gen: 7 },
  { id: 725, name: "litten", types: ["fire"], gen: 7 },
  { id: 726, name: "torracat", types: ["fire"], gen: 7 },
  { id: 727, name: "incineroar", types: ["fire", "dark"], gen: 7 },
  { id: 728, name: "popplio", types: ["water"], gen: 7 },
  { id: 729, name: "brionne", types: ["water"], gen: 7 },
  { id: 730, name: "primarina", types: ["water", "fairy"], gen: 7 },
  { id: 731, name: "pikipek", types: ["normal", "flying"], gen: 7 },
  { id: 732, name: "trumbeak", types: ["normal", "flying"], gen: 7 },
  { id: 733, name: "toucannon", types: ["normal", "flying"], gen: 7 },
  { id: 734, name: "yungoos", types: ["normal"], gen: 7 },
  { id: 735, name: "gumshoos", types: ["normal"], gen: 7 },
  { id: 736, name: "grubbin", types: ["bug"], gen: 7 },
  { id: 737, name: "charjabug", types: ["bug", "electric"], gen: 7 },
  { id: 738, name: "vikavolt", types: ["bug", "electric"], gen: 7 },
  { id: 739, name: "crabrawler", types: ["fighting"], gen: 7 },
  { id: 740, name: "crabominable", types: ["fighting", "ice"], gen: 7 },
  { id: 741, name: "oricorio", types: ["fire", "flying"], gen: 7 },
  { id: 742, name: "cutiefly", types: ["bug", "fairy"], gen: 7 },
  { id: 743, name: "ribombee", types: ["bug", "fairy"], gen: 7 },
  { id: 744, name: "rockruff", types: ["rock"], gen: 7 },
  { id: 745, name: "lycanroc", types: ["rock"], gen: 7 },
  { id: 746, name: "wishiwashi", types: ["water"], gen: 7 },
  { id: 747, name: "mareanie", types: ["poison", "water"], gen: 7 },
  { id: 748, name: "toxapex", types: ["poison", "water"], gen: 7 },
  { id: 749, name: "mudbray", types: ["ground"], gen: 7 },
  { id: 750, name: "mudsdale", types: ["ground"], gen: 7 },
  { id: 751, name: "dewpider", types: ["water", "bug"], gen: 7 },
  { id: 752, name: "araquanid", types: ["water", "bug"], gen: 7 },
  { id: 753, name: "fomantis", types: ["grass"], gen: 7 },
  { id: 754, name: "lurantis", types: ["grass"], gen: 7 },
  { id: 755, name: "morelull", types: ["grass", "fairy"], gen: 7 },
  { id: 756, name: "shiinotic", types: ["grass", "fairy"], gen: 7 },
  { id: 757, name: "salandit", types: ["poison", "fire"], gen: 7 },
  { id: 758, name: "salazzle", types: ["poison", "fire"], gen: 7 },
  { id: 759, name: "stufful", types: ["normal", "fighting"], gen: 7 },
  { id: 760, name: "bewear", types: ["normal", "fighting"], gen: 7 },
  { id: 761, name: "bounsweet", types: ["grass"], gen: 7 },
  { id: 762, name: "steenee", types: ["grass"], gen: 7 },
  { id: 763, name: "tsareena", types: ["grass"], gen: 7 },
  { id: 764, name: "comfey", types: ["fairy"], gen: 7 },
  { id: 765, name: "oranguru", types: ["normal", "psychic"], gen: 7 },
  { id: 766, name: "passimian", types: ["fighting"], gen: 7 },
  { id: 767, name: "wimpod", types: ["bug", "water"], gen: 7 },
  { id: 768, name: "golisopod", types: ["bug", "water"], gen: 7 },
  { id: 769, name: "sandygast", types: ["ghost", "ground"], gen: 7 },
  { id: 770, name: "palossand", types: ["ghost", "ground"], gen: 7 },
  { id: 771, name: "pyukumuku", types: ["water"], gen: 7 },
  { id: 772, name: "type: Null", types: ["normal"], gen: 7 },
  { id: 773, name: "silvally", types: ["normal"], gen: 7 },
  { id: 774, name: "minior", types: ["rock", "flying"], gen: 7 },
  { id: 775, name: "komala", types: ["normal"], gen: 7 },
  { id: 776, name: "turtonator", types: ["fire", "dragon"], gen: 7 },
  { id: 777, name: "togedemaru", types: ["electric", "steel"], gen: 7 },
  { id: 778, name: "mimikyu", types: ["ghost", "fairy"], gen: 7 },
  { id: 779, name: "bruxish", types: ["water", "psychic"], gen: 7 },
  { id: 780, name: "drampa", types: ["normal", "dragon"], gen: 7 },
  { id: 781, name: "dhelmise", types: ["ghost", "grass"], gen: 7 },
  { id: 782, name: "jangmo-o", types: ["dragon"], gen: 7 },
  { id: 783, name: "hakamo-o", types: ["dragon", "fighting"], gen: 7 },
  { id: 784, name: "kommo-o", types: ["dragon", "fighting"], gen: 7 },
  { id: 785, name: "tapu Koko", types: ["electric", "fairy"], gen: 7 },
  { id: 786, name: "tapu Lele", types: ["psychic", "fairy"], gen: 7 },
  { id: 787, name: "tapu Bulu", types: ["grass", "fairy"], gen: 7 },
  { id: 788, name: "tapu Fini", types: ["water", "fairy"], gen: 7 },
  { id: 789, name: "cosmog", types: ["psychic"], gen: 7 },
  { id: 790, name: "cosmoem", types: ["psychic"], gen: 7 },
  { id: 791, name: "solgaleo", types: ["psychic", "steel"], gen: 7 },
  { id: 792, name: "lunala", types: ["psychic", "ghost"], gen: 7 },
  { id: 793, name: "nihilego", types: ["rock", "poison"], gen: 7 },
  { id: 794, name: "buzzwole", types: ["bug", "fighting"], gen: 7 },
  { id: 795, name: "pheromosa", types: ["bug", "fighting"], gen: 7 },
  { id: 796, name: "xurkitree", types: ["electric"], gen: 7 },
  { id: 797, name: "celesteela", types: ["steel", "flying"], gen: 7 },
  { id: 798, name: "kartana", types: ["grass", "steel"], gen: 7 },
  { id: 799, name: "guzzlord", types: ["dark", "dragon"], gen: 7 },
  { id: 800, name: "necrozma", types: ["psychic"], gen: 7 },
  { id: 801, name: "magearna", types: ["steel", "fairy"], gen: 7 },
  { id: 802, name: "marshadow", types: ["fighting", "ghost"], gen: 7 },
  { id: 803, name: "poipole", types: ["poison"], gen: 7 },
  { id: 804, name: "naganadel", types: ["poison", "dragon"], gen: 7 },
  { id: 805, name: "stakataka", types: ["rock", "steel"], gen: 7 },
  { id: 806, name: "blacephalon", types: ["fire", "ghost"], gen: 7 },
  { id: 807, name: "zeraora", types: ["electric"], gen: 7 },
  { id: 808, name: "meltan", types: ["steel"], gen: 7 },
  { id: 809, name: "melmetal", types: ["steel"], gen: 7 },
  { id: 810, name: "grookey", types: ["grass"], gen: 8 },
  { id: 811, name: "thwackey", types: ["grass"], gen: 8 },
  { id: 812, name: "rillaboom", types: ["grass"], gen: 8 },
  { id: 813, name: "scorbunny", types: ["fire"], gen: 8 },
  { id: 814, name: "raboot", types: ["fire"], gen: 8 },
  { id: 815, name: "cinderace", types: ["fire"], gen: 8 },
  { id: 816, name: "sobble", types: ["water"], gen: 8 },
  { id: 817, name: "drizzile", types: ["water"], gen: 8 },
  { id: 818, name: "inteleon", types: ["water"], gen: 8 },
  { id: 819, name: "skwovet", types: ["normal"], gen: 8 },
  { id: 820, name: "greedent", types: ["normal"], gen: 8 },
  { id: 821, name: "rookidee", types: ["flying"], gen: 8 },
  { id: 822, name: "corvisquire", types: ["flying"], gen: 8 },
  { id: 823, name: "corviknight", types: ["flying", "steel"], gen: 8 },
  { id: 824, name: "blipbug", types: ["bug"], gen: 8 },
  { id: 825, name: "dottler", types: ["bug", "psychic"], gen: 8 },
  { id: 826, name: "orbeetle", types: ["bug", "psychic"], gen: 8 },
  { id: 827, name: "nickit", types: ["dark"], gen: 8 },
  { id: 828, name: "thievul", types: ["dark"], gen: 8 },
  { id: 829, name: "gossifleur", types: ["grass"], gen: 8 },
  { id: 830, name: "eldegoss", types: ["grass"], gen: 8 },
  { id: 831, name: "wooloo", types: ["normal"], gen: 8 },
  { id: 832, name: "dubwool", types: ["normal"], gen: 8 },
  { id: 833, name: "chewtle", types: ["water"], gen: 8 },
  { id: 834, name: "drednaw", types: ["water", "rock"], gen: 8 },
  { id: 835, name: "yamper", types: ["electric"], gen: 8 },
  { id: 836, name: "boltund", types: ["electric"], gen: 8 },
  { id: 837, name: "rolycoly", types: ["rock"], gen: 8 },
  { id: 838, name: "carkol", types: ["rock", "fire"], gen: 8 },
  { id: 839, name: "coalossal", types: ["rock", "fire"], gen: 8 },
  { id: 840, name: "applin", types: ["grass", "dragon"], gen: 8 },
  { id: 841, name: "flapple", types: ["grass", "dragon"], gen: 8 },
  { id: 842, name: "appletun", types: ["grass", "dragon"], gen: 8 },
  { id: 843, name: "silicobra", types: ["ground"], gen: 8 },
  { id: 844, name: "sandaconda", types: ["ground"], gen: 8 },
  { id: 845, name: "cramorant", types: ["flying", "water"], gen: 8 },
  { id: 846, name: "arrokuda", types: ["water"], gen: 8 },
  { id: 847, name: "barraskewda", types: ["water"], gen: 8 },
  { id: 848, name: "toxel", types: ["electric", "poison"], gen: 8 },
  { id: 849, name: "toxtricity", types: ["electric", "poison"], gen: 8 },
  { id: 850, name: "sizzlipede", types: ["fire", "bug"], gen: 8 },
  { id: 851, name: "centiskorch", types: ["fire", "bug"], gen: 8 },
  { id: 852, name: "clobbopus", types: ["fighting"], gen: 8 },
  { id: 853, name: "grapploct", types: ["fighting"], gen: 8 },
  { id: 854, name: "sinistea", types: ["ghost"], gen: 8 },
  { id: 855, name: "polteageist", types: ["ghost"], gen: 8 },
  { id: 856, name: "hatenna", types: ["psychic"], gen: 8 },
  { id: 857, name: "hattrem", types: ["psychic"], gen: 8 },
  { id: 858, name: "hatterene", types: ["psychic", "fairy"], gen: 8 },
  { id: 859, name: "impidimp", types: ["dark", "fairy"], gen: 8 },
  { id: 860, name: "morgrem", types: ["dark", "fairy"], gen: 8 },
  { id: 861, name: "grimmsnarl", types: ["dark", "fairy"], gen: 8 },
  { id: 862, name: "obstagoon", types: ["dark", "normal"], gen: 8 },
  { id: 863, name: "perrserker", types: ["steel"], gen: 8 },
  { id: 864, name: "cursola", types: ["ghost"], gen: 8 },
  { id: 865, name: "sirfetchd", types: ["fighting"], gen: 8 },
  { id: 866, name: "mr. Rime", types: ["ice", "psychic"], gen: 8 },
  { id: 867, name: "runerigus", types: ["ground", "ghost"], gen: 8 },
  { id: 868, name: "milcery", types: ["fairy"], gen: 8 },
  { id: 869, name: "alcremie", types: ["fairy"], gen: 8 },
  { id: 870, name: "falinks", types: ["fighting"], gen: 8 },
  { id: 871, name: "pincurchin", types: ["electric"], gen: 8 },
  { id: 872, name: "snom", types: ["ice", "bug"], gen: 8 },
  { id: 873, name: "frosmoth", types: ["ice", "bug"], gen: 8 },
  { id: 874, name: "stonjourner", types: ["rock"], gen: 8 },
  { id: 875, name: "eiscue", types: ["ice"], gen: 8 },
  { id: 876, name: "indeedee", types: ["psychic", "normal"], gen: 8 },
  { id: 877, name: "morpeko", types: ["electric", "dark"], gen: 8 },
  { id: 878, name: "cufant", types: ["steel"], gen: 8 },
  { id: 879, name: "copperajah", types: ["steel"], gen: 8 },
  { id: 880, name: "dracozolt", types: ["electric", "dragon"], gen: 8 },
  { id: 881, name: "arctozolt", types: ["electric", "ice"], gen: 8 },
  { id: 882, name: "dracovish", types: ["water", "dragon"], gen: 8 },
  { id: 883, name: "arctovish", types: ["water", "ice"], gen: 8 },
  { id: 884, name: "duraludon", types: ["steel", "dragon"], gen: 8 },
  { id: 885, name: "dreepy", types: ["dragon", "ghost"], gen: 8 },
  { id: 886, name: "drakloak", types: ["dragon", "ghost"], gen: 8 },
  { id: 887, name: "dragapult", types: ["dragon", "ghost"], gen: 8 },
  { id: 888, name: "zacian", types: ["fairy"], gen: 8 },
  { id: 889, name: "zamazenta", types: ["fighting"], gen: 8 },
  { id: 890, name: "eternatus", types: ["poison", "dragon"], gen: 8 },
  { id: 891, name: "kubfu", types: ["fighting"], gen: 8 },
  { id: 892, name: "urshifu", types: ["fighting", "dark"], gen: 8 },
  { id: 893, name: "zarude", types: ["dark", "grass"], gen: 8 },
  { id: 894, name: "regieleki", types: ["electric"], gen: 8 },
  { id: 895, name: "regidrago", types: ["dragon"], gen: 8 },
  { id: 896, name: "glastrier", types: ["ice"], gen: 8 },
  { id: 897, name: "spectrier", types: ["ghost"], gen: 8 },
  { id: 898, name: "calyrex", types: ["psychic", "grass"], gen: 8 },
  { id: 899, name: "wyrdeer", types: ["normal", "psychic"], gen: 8 },
  { id: 900, name: "kleavor", types: ["bug", "rock"], gen: 8 },
  { id: 901, name: "ursaluna", types: ["ground", "normal"], gen: 8 },
  { id: 902, name: "basculegion", types: ["water", "ghost"], gen: 8 },
  { id: 903, name: "sneasler", types: ["fighting", "poison"], gen: 8 },
  { id: 904, name: "overqwil", types: ["dark", "poison"], gen: 8 },
  { id: 905, name: "enamorus", types: ["fairy", "flying"], gen: 8 },
  { id: 906, name: "sprigatito", types: ["grass"], gen: 9 },
  { id: 907, name: "floragato", types: ["grass"], gen: 9 },
  { id: 908, name: "meowscarada", types: ["grass", "dark"], gen: 9 },
  { id: 909, name: "fuecoco", types: ["fire"], gen: 9 },
  { id: 910, name: "crocalor", types: ["fire"], gen: 9 },
  { id: 911, name: "skeledirge", types: ["fire", "ghost"], gen: 9 },
  { id: 912, name: "quaxly", types: ["water"], gen: 9 },
  { id: 913, name: "quaxwell", types: ["water"], gen: 9 },
  { id: 914, name: "quaquaval", types: ["water", "fighting"], gen: 9 },
  { id: 915, name: "lechonk", types: ["normal"], gen: 9 },
  { id: 916, name: "oinkologne", types: ["normal"], gen: 9 },
  { id: 917, name: "tarountula", types: ["bug"], gen: 9 },
  { id: 918, name: "spidops", types: ["bug"], gen: 9 },
  { id: 919, name: "nymble", types: ["bug"], gen: 9 },
  { id: 920, name: "lokix", types: ["bug", "dark"], gen: 9 },
  { id: 921, name: "pawmi", types: ["electric"], gen: 9 },
  { id: 922, name: "pawmo", types: ["electric", "fighting"], gen: 9 },
  { id: 923, name: "pawmot", types: ["electric", "fighting"], gen: 9 },
  { id: 924, name: "tandemaus", types: ["normal"], gen: 9 },
  { id: 925, name: "maushold", types: ["normal"], gen: 9 },
  { id: 926, name: "fidough", types: ["fairy"], gen: 9 },
  { id: 927, name: "dachsbun", types: ["fairy"], gen: 9 },
  { id: 928, name: "smoliv", types: ["grass", "normal"], gen: 9 },
  { id: 929, name: "dolliv", types: ["grass", "normal"], gen: 9 },
  { id: 930, name: "arboliva", types: ["grass", "normal"], gen: 9 },
  { id: 931, name: "squawkabilly", types: ["normal", "flying"], gen: 9 },
  { id: 932, name: "nacli", types: ["rock"], gen: 9 },
  { id: 933, name: "naclstack", types: ["rock"], gen: 9 },
  { id: 934, name: "garganacl", types: ["rock"], gen: 9 },
  { id: 935, name: "charcadet", types: ["fire"], gen: 9 },
  { id: 936, name: "armarouge", types: ["fire", "psychic"], gen: 9 },
  { id: 937, name: "ceruledge", types: ["fire", "ghost"], gen: 9 },
  { id: 938, name: "tadbulb", types: ["electric"], gen: 9 },
  { id: 939, name: "bellibolt", types: ["electric"], gen: 9 },
  { id: 940, name: "wattrel", types: ["electric", "flying"], gen: 9 },
  { id: 941, name: "kilowattrel", types: ["electric", "flying"], gen: 9 },
  { id: 942, name: "maschiff", types: ["dark"], gen: 9 },
  { id: 943, name: "mabosstiff", types: ["dark"], gen: 9 },
  { id: 944, name: "shroodle", types: ["poison", "normal"], gen: 9 },
  { id: 945, name: "grafaiai", types: ["poison", "normal"], gen: 9 },
  { id: 946, name: "bramblin", types: ["grass", "ghost"], gen: 9 },
  { id: 947, name: "brambleghast", types: ["grass", "ghost"], gen: 9 },
  { id: 948, name: "toedscool", types: ["ground", "grass"], gen: 9 },
  { id: 949, name: "toedscruel", types: ["ground", "grass"], gen: 9 },
  { id: 950, name: "klawf", types: ["rock"], gen: 9 },
  { id: 951, name: "capsakid", types: ["grass"], gen: 9 },
  { id: 952, name: "scovillain", types: ["grass", "fire"], gen: 9 },
  { id: 953, name: "rellor", types: ["bug"], gen: 9 },
  { id: 954, name: "rabsca", types: ["bug", "psychic"], gen: 9 },
  { id: 955, name: "flittle", types: ["psychic"], gen: 9 },
  { id: 956, name: "espathra", types: ["psychic"], gen: 9 },
  { id: 957, name: "tinkatink", types: ["fairy", "steel"], gen: 9 },
  { id: 958, name: "tinkatuff", types: ["fairy", "steel"], gen: 9 },
  { id: 959, name: "tinkaton", types: ["fairy", "steel"], gen: 9 },
  { id: 960, name: "wiglett", types: ["water"], gen: 9 },
  { id: 961, name: "wugtrio", types: ["water"], gen: 9 },
  { id: 962, name: "bombirdier", types: ["flying", "dark"], gen: 9 },
  { id: 963, name: "finizen", types: ["water"], gen: 9 },
  { id: 964, name: "palafin", types: ["water"], gen: 9 },
  { id: 965, name: "varoom", types: ["steel", "poison"], gen: 9 },
  { id: 966, name: "revavroom", types: ["steel", "poison"], gen: 9 },
  { id: 967, name: "cyclizar", types: ["dragon", "normal"], gen: 9 },
  { id: 968, name: "orthworm", types: ["steel"], gen: 9 },
  { id: 969, name: "glimmet", types: ["rock", "poison"], gen: 9 },
  { id: 970, name: "glimmora", types: ["rock", "poison"], gen: 9 },
  { id: 971, name: "greavard", types: ["ghost"], gen: 9 },
  { id: 972, name: "houndstone", types: ["ghost"], gen: 9 },
  { id: 973, name: "flamigo", types: ["flying", "fighting"], gen: 9 },
  { id: 974, name: "cetoddle", types: ["ice"], gen: 9 },
  { id: 975, name: "cetitan", types: ["ice"], gen: 9 },
  { id: 976, name: "veluza", types: ["water", "psychic"], gen: 9 },
  { id: 977, name: "dondozo", types: ["water"], gen: 9 },
  { id: 978, name: "tatsugiri", types: ["dragon", "water"], gen: 9 },
  { id: 979, name: "annihilape", types: ["fighting", "ghost"], gen: 9 },
  { id: 980, name: "clodsire", types: ["poison", "ground"], gen: 9 },
  { id: 981, name: "farigiraf", types: ["normal", "psychic"], gen: 9 },
  { id: 982, name: "dudunsparce", types: ["normal"], gen: 9 },
  { id: 983, name: "kingambit", types: ["dark", "steel"], gen: 9 },
  { id: 984, name: "great Tusk", types: ["ground", "fighting"], gen: 9 },
  { id: 985, name: "scream Tail", types: ["fairy", "psychic"], gen: 9 },
  { id: 986, name: "brute Bonnet", types: ["grass", "dark"], gen: 9 },
  { id: 987, name: "flutter Mane", types: ["ghost", "fairy"], gen: 9 },
  { id: 988, name: "slither Wing", types: ["bug", "fighting"], gen: 9 },
  { id: 989, name: "sandy Shocks", types: ["electric", "ground"], gen: 9 },
  { id: 990, name: "iron Treads", types: ["ground", "steel"], gen: 9 },
  { id: 991, name: "iron Bundle", types: ["ice", "water"], gen: 9 },
  { id: 992, name: "iron Hands", types: ["fighting", "electric"], gen: 9 },
  { id: 993, name: "iron Jugulis", types: ["dark", "flying"], gen: 9 },
  { id: 994, name: "iron Moth", types: ["fire", "poison"], gen: 9 },
  { id: 995, name: "iron Thorns", types: ["rock", "electric"], gen: 9 },
  { id: 996, name: "frigibax", types: ["dragon", "ice"], gen: 9 },
  { id: 997, name: "arctibax", types: ["dragon", "ice"], gen: 9 },
  { id: 998, name: "baxcalibur", types: ["dragon", "ice"], gen: 9 },
  { id: 999, name: "gimmighoul", types: ["ghost"], gen: 9 },
  { id: 1000, name: "gholdengo", types: ["steel", "ghost"], gen: 9 },
  { id: 1001, name: "wo-Chien", types: ["dark", "grass"], gen: 9 },
  { id: 1002, name: "chien-Pao", types: ["dark", "ice"], gen: 9 },
  { id: 1003, name: "ting-Lu", types: ["dark", "ground"], gen: 9 },
  { id: 1004, name: "chi-Yu", types: ["dark", "fire"], gen: 9 },
  { id: 1005, name: "roaring Moon", types: ["dragon", "dark"], gen: 9 },
  { id: 1006, name: "iron Valiant", types: ["fairy", "fighting"], gen: 9 },
  { id: 1007, name: "koraidon", types: ["fighting", "dragon"], gen: 9 },
  { id: 1008, name: "miraidon", types: ["electric", "dragon"], gen: 9 },
];
